name: Deploy to prod

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: Deploy to prod

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ vars.SERVER_HOST }}
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /opt/invincible-voice
            git pull origin main
            docker compose --env-file .env.prod -f docker-compose.yml -f docker-compose.prod.yml up -d --build
            docker image prune -f
