name: Lint

on:
  pull_request:
  push:
    branches:
      - main
      - staging

jobs:
  lint-backend:
    name: Lint Backend (Python)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: astral-sh/setup-uv@v4
        with:
          version: "latest"

      - name: Install pre-commit
        run: uvx pre-commit install

      - name: Run pre-commit
        run: uvx pre-commit run --all-files


  lint-frontend:
    name: Lint Frontend (JavaScript/TypeScript)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: latest

      - name: Install dependencies
        working-directory: services/frontend
        run: pnpm install

      - name: Run ESLint
        working-directory: services/frontend
        run: pnpm lint

      - name: Build frontend
        working-directory: services/frontend
        run: pnpm build

  build-docker-images:
    name: Build docker images
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build the docker images
        env:
          COMMIT_SHA: ${{ github.sha }}
          BACKEND_REPLICAS_COUNT: 8
        run: docker compose -f swarm-config.yml build
